private
error: aError
	error := aError.
